const P256_CURVE = { name: 'ECDSA', namedCurve: 'P-256' };
const HASH_ALGO = { name: 'SHA-256' };

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

function base64UrlEncode(bytes: Uint8Array): string {
  return btoa(String.fromCharCode(...bytes))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
}

function base64UrlDecode(str: string): Uint8Array {
  const b64 = str.replace(/-/g, '+').replace(/_/g, '/');
  const padded = b64 + '='.repeat((4 - b64.length % 4) % 4);
  return Uint8Array.from(atob(padded), c => c.charCodeAt(0));
}

async function sha256(data: string): Promise<string> {
  const encoder = new TextEncoder();
  const hashBuffer = await crypto.subtle.digest('SHA-256', encoder.encode(data));
  return bytesToHex(new Uint8Array(hashBuffer));
}

interface StoredKeyPair {
  privateKeyJwk: JsonWebKey;
  publicKeyHex: string;
  address: string;
}

const keyCache = new Map<string, StoredKeyPair>();

export async function generateKeyPair(): Promise<{ privateKey: string; publicKey: string; address: string }> {
  const keyPair = await crypto.subtle.generateKey(P256_CURVE, true, ['sign', 'verify']);
  
  const jwk = await crypto.subtle.exportKey('jwk', keyPair.privateKey);
  const dBytes = base64UrlDecode(jwk.d!);
  const privateKey = bytesToHex(dBytes);
  
  const publicKeyRaw = await crypto.subtle.exportKey('raw', keyPair.publicKey);
  const publicKey = bytesToHex(new Uint8Array(publicKeyRaw));
  
  const address = (await sha256(publicKey)).slice(0, 40);
  
  keyCache.set(privateKey, { privateKeyJwk: jwk, publicKeyHex: publicKey, address });
  
  return { privateKey, publicKey, address };
}

async function importPrivateKeyFromJwk(jwk: JsonWebKey): Promise<{ privateKey: CryptoKey; publicKey: CryptoKey }> {
  const privateKey = await crypto.subtle.importKey(
    'jwk',
    jwk,
    P256_CURVE,
    true,
    ['sign']
  );
  
  const pubJwk = { ...jwk };
  delete pubJwk.d;
  pubJwk.key_ops = ['verify'];
  
  const publicKey = await crypto.subtle.importKey(
    'jwk',
    pubJwk,
    P256_CURVE,
    true,
    ['verify']
  );
  
  return { privateKey, publicKey };
}

export async function getAddressFromPrivateKey(privateKeyHex: string): Promise<{ publicKey: string; address: string }> {
  const cached = keyCache.get(privateKeyHex);
  if (cached) {
    return { publicKey: cached.publicKeyHex, address: cached.address };
  }
  
  const stored = localStorage.getItem(`rinku_key_${privateKeyHex}`);
  if (stored) {
    try {
      const parsed: StoredKeyPair = JSON.parse(stored);
      keyCache.set(privateKeyHex, parsed);
      return { publicKey: parsed.publicKeyHex, address: parsed.address };
    } catch (e) {
      console.warn('Failed to parse stored key, generating new');
    }
  }
  
  const kp = await generateKeyPair();
  if (kp.privateKey === privateKeyHex) {
    return { publicKey: kp.publicKey, address: kp.address };
  }
  
  throw new Error('Private key not recognized. Please use a key generated by this wallet or import via full JWK.');
}

export async function signMessage(privateKeyHex: string, message: string): Promise<string> {
  const cached = keyCache.get(privateKeyHex);
  if (!cached) {
    throw new Error('Private key not in cache. Generate a new key or import a saved wallet.');
  }
  
  const { privateKey } = await importPrivateKeyFromJwk(cached.privateKeyJwk);
  const encoder = new TextEncoder();
  const data = encoder.encode(message);
  
  const signature = await crypto.subtle.sign(
    { ...P256_CURVE, hash: HASH_ALGO },
    privateKey,
    data
  );
  
  return bytesToHex(new Uint8Array(signature));
}

export function saveKeyToStorage(privateKeyHex: string): void {
  const cached = keyCache.get(privateKeyHex);
  if (cached) {
    localStorage.setItem(`rinku_key_${privateKeyHex}`, JSON.stringify(cached));
  }
}

export function loadKeyFromStorage(privateKeyHex: string): boolean {
  const stored = localStorage.getItem(`rinku_key_${privateKeyHex}`);
  if (stored) {
    try {
      const parsed: StoredKeyPair = JSON.parse(stored);
      keyCache.set(privateKeyHex, parsed);
      return true;
    } catch (e) {
      return false;
    }
  }
  return false;
}

export async function hashTransaction(txJson: string): Promise<string> {
  return sha256(txJson);
}

export interface TransactionPayload {
  from: string;
  to: string;
  amount: number;
  nonce: number;
  timestamp: number;
  parents: string[];
  kind?: 'transfer' | 'stake' | 'unstake' | 'contract' | 'consolidation' | 'reward';
  gasLimit?: number;
  gasPrice?: number;
  data?: string;
}

export interface SignedTransaction {
  tx: TransactionPayload;
  hash: string;
  signature: string;
}

export async function createSignedTransaction(
  privateKeyHex: string,
  payload: Omit<TransactionPayload, 'from' | 'timestamp'>
): Promise<SignedTransaction> {
  const keyInfo = await getAddressFromPrivateKey(privateKeyHex);
  
  const tx: TransactionPayload = {
    ...payload,
    from: keyInfo.address,
    timestamp: Date.now(),
  };
  
  const txJson = JSON.stringify(tx);
  const hash = await hashTransaction(txJson);
  const signature = await signMessage(privateKeyHex, txJson);
  
  return { tx, hash, signature };
}

export function validatePrivateKey(hex: string): boolean {
  if (!/^[0-9a-fA-F]{64}$/.test(hex)) return false;
  return true;
}
